# AI病历质控系统生产环境配置

server:
  port: 8080

spring:
  application:
    name: ai-medical-score
  
  # 数据库配置 - 生产环境
  datasource:
    url: jdbc:mysql://172.16.1.15:3306/bailun?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 44033@lzd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境使用 validate
    show-sql: false      # 生产环境关闭SQL日志
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # Flyway数据库迁移
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Redis配置 - 生产环境
  redis:
    host: 172.16.1.15
    port: 6379
    database: 15
    password: redis123
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms

# AI服务配置 - 生产环境
ai:
  # DeepSeek AI配置
  deepseek:
    api-url: https://api.siliconflow.cn/v1/chat/completions
    api-key: sk-stwdcstqnkcztrsqsrmosrcpekiacrualyzzvsgfmzjvuurv
    model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    temperature: 0.1
    max-tokens: 4000
    timeout: 30000  # 30秒超时
    retry-count: 1  # 重试1次
    
  # HMS系统配置
  hms:
    api-url: http://172.16.1.13:10086
    token: d440578b-5ab3-4254-adf9-d9527503ae84
    dept-id: 100

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      simple:
        enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.bailun.ai: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: logs/ai-medical-score.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30 