# AI病历质控系统生产环境配置

server:
  port: 8080

spring:
  application:
    name: ai-medical-score
  
  # 数据库配置 - 生产环境
  datasource:
    url: jdbc:mysql://172.16.1.15:3306/bailun?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 44033@lzd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境使用 validate
    show-sql: false      # 生产环境关闭SQL日志
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # Flyway数据库迁移
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Redis配置 - 生产环境
  redis:
    host: 172.16.1.15
    port: 6379
    database: 15
    password: redis123
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms

# AI服务配置 - 生产环境
ai:
  # DeepSeek AI配置
  deepseek:
    api-url: https://api.siliconflow.cn/v1/chat/completions
    api-key: sk-stwdcstqnkcztrsqsrmosrcpekiacrualyzzvsgfmzjvuurv
    # model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    model: Qwen/Qwen3-8B
    temperature: 0.1
    max-tokens: 4000
    timeout: 30000  # 30秒超时
    retry-count: 1  # 重试1次
    
  # HMS系统配置
  hms:
    api-url: http://172.16.1.13:10086
    token: 97285ff9-240a-4546-9f14-a9b858397716
    systemdeptid: 127

  # 提示词模板配置 - 生产环境
  prompt:
    template:
      system: |
        你是一个专业的医疗质控专家，需要根据病历信息进行评分。
        
        ## 评分维度
        请按照以下8个维度进行评分：
        ${scoring_dimensions}
        
        ## 数据字段说明
        患者基础信息字段说明：
        ${patient_info_fields}
        
        诊疗信息字段说明：
        ${treatment_info_fields}
        
        ## 输出格式要求
        ${output_format}
        
        ## 评分标准
        ${scoring_criteria}
        
      user: "请根据以下病历信息进行评分：\n患者信息：${patient_data}\n诊疗信息：${treatment_data}"
      
    variables:
      scoring_dimensions: |
        1. 主诉 (10分)：评估主诉的完整性和规范性
        2. 病史 (20分)：包括现病史、既往史、过敏史等
        3. 体格检查 (15分)：评估体格检查记录的完整性
        4. 辅助检查 (5分)：评估检验检查结果的完整性
        5. 诊断 (15分)：评估诊断的准确性和完整性
        6. 处理 (20分)：评估治疗方案的合理性
        7. 总体评价 (5分)：评估病历的整体质量
        8. 其他 (10分)：评估其他方面如签名、规范性等
        
      patient_info_fields: |
        - name: 患者姓名
        - allergy: 过敏史
        - tumor: 肿瘤史  
        - smoking: 吸烟史
        - tipple: 饮酒史
        - dialyzeAge: 透析龄
        - stature: 身高
        - initWeight: 体重
        - bloodType: 血型
        - rh: Rh血型
        - erythrocyte: 红细胞计数
        
      treatment_info_fields: |
        - mainSuit: 主诉
        - diagnosis: 诊断
        - initDiagnosis: 初步诊断
        - presentMedical: 现病史
        - treatmentHistory: 治疗史
        - treatmentHistoryContent: 治疗史详情
        - tentativeDiagnosis: 初步诊断详情
        
      output_format: |
        请严格按照以下JSON格式返回评分结果，不要包含任何其他文字：
        {
          "totalScore": 总分数字,
          "level": "甲级/乙级/丙级",
          "details": [
            {
              "item": "主诉",
              "fullScore": 10,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "病史",
              "fullScore": 20,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "体格检查",
              "fullScore": 15,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "辅助检查",
              "fullScore": 5,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "诊断",
              "fullScore": 15,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "处理",
              "fullScore": 20,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "总体评价",
              "fullScore": 5,
              "score": 实际得分,
              "deduction": "扣分说明"
            },
            {
              "item": "其他",
              "fullScore": 10,
              "score": 实际得分,
              "deduction": "扣分说明"
            }
          ]
        }
        
      scoring_criteria: |
        评分标准：
        - 甲级：90-100分
        - 乙级：75-89分  
        - 丙级：60-74分
        - 不合格：60分以下

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      simple:
        enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.bailun.ai: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: logs/ai-medical-score.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30 