server:
  port: 8080

spring:
  application:
    name: ai-medical-score
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://172.16.1.15:3306/bailun?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 44033@lzd
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Flyway数据库迁移
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  # Redis配置
  redis:
    host: 172.16.1.15
    port: 6379
    database: 15
    password: redis123
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    
# AI配置
ai:
  deepseek:
    api-url: https://api.siliconflow.cn
    api-key: sk-stwdcstqnkcztrsqsrmosrcpekiacrualyzzvsgfmzjvuurv
    model: deepseek-ai/DeepSeek-R1
    retry-count: 1
    timeout: 600000
    temperature: 0.1
    max-tokens: 16000
    # Mock模式开关 - 设为true时使用模拟AI响应，设为false时使用真实AI API
    mock:
      enabled: false
  
  hms:
    api-url: http://172.16.1.13:10086
    token: 97285ff9-240a-4546-9f14-a9b858397716
    systemdeptid: 127

  # 提示词模板配置
  prompt:
    template:
      system: |
        你是一位资深的医疗质控专家，负责对住院病历进行质量评估。请严格按照以下评分标准进行评估：

        ## 评分维度和标准
        1. **主诉 (10分)**: 主诉是否简明扼要、准确反映患者就诊原因
        2. **病史 (20分)**: 现病史、既往史、个人史、家族史是否详细完整
        3. **体格检查 (15分)**: 体格检查记录是否全面、准确、规范
        4. **诊断 (15分)**: 诊断是否准确、完整、符合疾病命名规范
        5. **处理 (20分)**: 治疗方案是否合理、规范、有效
        6. **其他 (20分)**: 病历书写规范性、完整性等其他方面

        ## 评分等级
        - 甲级：90-100分，病历质量优秀
        - 乙级：75-89分，病历质量良好
        - 丙级：60-74分，病历质量一般
        - 不合格：60分以下

        ## 输出格式
        请严格按照以下JSON格式返回评估结果：
        ```json
        {
          "totalScore": 总分数字,
          "level": "甲级/乙级/丙级",
          "details": [
            {
              "item": "主诉",
              "fullScore": 10,
              "score": 实际得分,
              "deduction": "扣分原因说明"
            }
          ]
        }
        ```
        
      user: "请对以下病历进行质量评估：\n患者信息：${patient_data}\n诊疗信息：${treatment_data}"
      
    variables:
      scoring_dimensions: "主诉、病史、检查、诊断、处理"
      patient_info_fields: "基本信息"
      treatment_info_fields: "诊疗信息"
      output_format: "JSON格式"
      scoring_criteria: "甲级90+，乙级75+，丙级60+"

# 日志配置
logging:
  level:
    com.bailun.ai: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 